<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a8fa54a3-743f-4f1d-b837-9d78a1979f98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Alexandre Christie Primo Steel AC 1029 BRGSL Couple Silver Dial Rose Gold Stainless Steel Strap&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/section[2]/div[2]/div/div/div/div[2]/div/div/div/a/div/div/div/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8cc90d50-6818-451e-b00d-c71fd67ad056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.jamtangan.com/images/product/alexandre-christie/ACF-1029-BRGSL/ACF-1029-BRGSL.jpg</value>
      <webElementGuid>517d14ae-64a3-4b9c-b58b-dc78375be8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Alexandre Christie Primo Steel AC 1029 BRGSL Couple Silver Dial Rose Gold Stainless Steel Strap</value>
      <webElementGuid>ea9ef7d4-c7d9-46d5-b29e-cff79511fc37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>229</value>
      <webElementGuid>f707d043-b468-48d7-abaa-242cfc61c861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>43316c70-fc5b-41bd-8bc4-ead8b8159e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>5e406884-1a01-4f62-a2f8-f03f71fbdfd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;min-h-screen flex flex-col bg-neutral-1000&quot;]/div[@class=&quot;mw-layout-content&quot;]/div[@class=&quot;homepage text-sm text-neutral-300 grid&quot;]/section[@class=&quot;featured-products mt-1 md:mt-3.5 px-4 md:px-0&quot;]/div[@class=&quot;lower&quot;]/div[@class=&quot;slick-slider product-slider active-slide-list slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active&quot;]/div[1]/div[@class=&quot;product p-2 h-full&quot;]/div[@class=&quot;relative h-full rounded-2 bg-neutral-900&quot;]/a[1]/div[@class=&quot;card relative rounded-2 bg-neutral-900 product-card-container cursor-pointer h-full&quot;]/div[@class=&quot;product-card relative&quot;]/div[@class=&quot;relative pt-6 px-2 md:px-4&quot;]/div[@class=&quot;box-img text-neutral-700 text-xs flex items-center&quot;]/picture[1]/img[1]</value>
      <webElementGuid>c982196b-5cfa-432a-bbc4-c802576fd05a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/section[2]/div[2]/div/div/div/div[2]/div/div/div/a/div/div/div/div/picture/img</value>
      <webElementGuid>d70544c4-5dc6-4880-8b59-325a0991a25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Alexandre Christie Primo Steel AC 1029 BRGSL Couple Silver Dial Rose Gold Stainless Steel Strap']</value>
      <webElementGuid>4ab3f9e2-466f-4b0d-8707-bfaa542ca479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/div/div/div/div/picture/img</value>
      <webElementGuid>86d5c088-94dc-4e07-ad37-f2246601ac47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.jamtangan.com/images/product/alexandre-christie/ACF-1029-BRGSL/ACF-1029-BRGSL.jpg' and @alt = 'Alexandre Christie Primo Steel AC 1029 BRGSL Couple Silver Dial Rose Gold Stainless Steel Strap']</value>
      <webElementGuid>0b59c28e-def3-4b04-812f-2793230a64a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
