<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verifikasi WhatsApp_w-12 p-3 text-cen_c67940</name>
   <tag></tag>
   <elementGuidId>5067e96b-b4d1-44d4-b61a-75e485e207a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.w-12.p-3.text-center.text-sm.text-neutral-300.bg-neutral-800.active.rounded.border-1.qa-otp-field.border-neutral-700</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75a58763-af94-487d-902f-fd40a1112198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9c0d179c-8da9-4bff-b9e1-1055f0a772bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>8432b0c4-05a5-4a1e-97da-c1dfe683d208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b3acdd7a-9f41-4406-ae7e-1f693e14e100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-12 p-3 text-center text-sm text-neutral-300 bg-neutral-800 active rounded border-1 qa-otp-field border-neutral-700</value>
      <webElementGuid>d2f7e324-f71a-4065-a210-3528bb0ccc3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6b0a94b5-56b0-4dba-abee-4106325a7ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>otp-input-0</value>
      <webElementGuid>cf8eddee-3ea2-4d5a-a74d-3100bd0a8f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>803ed95a-b82c-4357-81cd-d15c42272dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[2]/div[@class=&quot;modal fixed h-full w-full top-0 left-0 flex items-center justify-center bg-neutral-1000 bg-opacity-50&quot;]/div[@class=&quot;content relative bg-clip-padding outline-none&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;relative rounded-4 modal-container-wrap p-6 my-8 max-w-sm bg-neutral-900&quot;]/div[1]/div[1]/div[@class=&quot;mb-8&quot;]/div[@class=&quot;otp-input&quot;]/div[@class=&quot;flex flex-wrap&quot;]/div[@class=&quot;flex items-center flex-grow p-0.5&quot;]/input[@class=&quot;w-12 p-3 text-center text-sm text-neutral-300 bg-neutral-800 active rounded border-1 qa-otp-field border-neutral-700&quot;]</value>
      <webElementGuid>46ba6d71-dddf-4c5a-8c70-0a5b432f5030</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='0']</value>
      <webElementGuid>0f43fd49-6eed-458e-b92f-fc2f839076c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div[2]/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>2c600df5-b94d-4fad-aeae-5dc42dcb4793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>51b7b52b-1500-4412-b5af-db35402a1587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>e5fbe97d-74e1-48fc-82a6-53777ef5e51c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
