<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nanti Saja</name>
   <tag></tag>
   <elementGuidId>042e1749-43f8-44fb-b1ec-2912ba4b07ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='moeRemoveBanner()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa42a13e-000b-4e3e-92a5-3a79acebf92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>moeRemoveBanner()</value>
      <webElementGuid>22813cf2-1cb5-41c6-b0b7-ee9f87b545dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>{'color': webPushPreview['bannerv2']['web']['closeButton']['color'],'background':webPushPreview['bannerv2']['web']['closeButton']['backgroundColor']}</value>
      <webElementGuid>b861f687-39a2-48e0-93c3-9768bc6a52de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>85757bc2-35cf-4aae-ad1d-072f681b0749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nanti Saja</value>
      <webElementGuid>73761a97-c62e-423c-a360-0f62df828a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktopBannerWrapped&quot;)/div[1]/div[3]/div[2]/button[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>636dc4ec-ca98-4fbf-a49b-90b7150bd235</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='moeRemoveBanner()']</value>
      <webElementGuid>f360db09-f401-4f5c-8775-86b9d9c9e2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='desktopBannerWrapped']/div/div[3]/div[2]/button</value>
      <webElementGuid>4c69f300-50cb-4bc4-9628-3845ff20165a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powered by'])[1]/following::button[1]</value>
      <webElementGuid>3fd18c43-58cd-4746-b209-c971059f5ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktivasi Notifikasi Website'])[1]/following::button[1]</value>
      <webElementGuid>5f2beb03-06e3-4120-adad-60dfec447711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Izinkan'])[1]/preceding::button[1]</value>
      <webElementGuid>d2fde5aa-3df7-4b3c-906d-b6ef92c0ab68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi Pembayaran'])[1]/preceding::button[2]</value>
      <webElementGuid>8c9956ff-98a0-440e-a25f-756da8bce45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nanti Saja']/parent::*</value>
      <webElementGuid>f9b01d51-ccec-4bf1-aec7-15a60731ac1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>22bade76-7e7c-424e-8ab7-6f8fb29ab3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Nanti Saja' or . = 'Nanti Saja')]</value>
      <webElementGuid>98410cab-aa54-4b0e-949e-dfb47a408f7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
