<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nanti Saja</name>
   <tag></tag>
   <elementGuidId>4fea8b53-bce7-4b74-bbe3-cff706ce5c82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='moeRemoveBanner()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>106c45b9-3a40-4838-834c-a99a7f00bfd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>moeRemoveBanner()</value>
      <webElementGuid>51671802-2db0-473d-9af3-1f4a94b9ba0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>{'color': webPushPreview['bannerv2']['web']['closeButton']['color'],'background':webPushPreview['bannerv2']['web']['closeButton']['backgroundColor']}</value>
      <webElementGuid>7102bfbd-b393-4a33-aa64-89c340587641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>fccbc48d-dfd5-4b58-bcc1-ba9228ae0548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nanti Saja</value>
      <webElementGuid>632277eb-285e-4059-98a0-ba1a1130194b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktopBannerWrapped&quot;)/div[1]/div[3]/div[2]/button[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>12a5a2d1-0fa8-45a6-9259-861a63035785</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='moeRemoveBanner()']</value>
      <webElementGuid>38a78ae9-7f5b-4489-b022-1cbce6fd4660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='desktopBannerWrapped']/div/div[3]/div[2]/button</value>
      <webElementGuid>560f9d56-ec5d-469e-aaeb-f1d75c1ca795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powered by'])[1]/following::button[1]</value>
      <webElementGuid>fd0bf0bf-4bf1-44ef-9ce1-1bfc581fbe7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktivasi Notifikasi Website'])[1]/following::button[1]</value>
      <webElementGuid>79943f4f-c932-4d3c-90d8-f60e3fde64ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Izinkan'])[1]/preceding::button[1]</value>
      <webElementGuid>c4b6508c-58f5-414e-b10e-fc053fd9b117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi Pembayaran'])[1]/preceding::button[2]</value>
      <webElementGuid>82a9334e-4933-4db0-a054-24cf8ca383b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nanti Saja']/parent::*</value>
      <webElementGuid>ec156f4e-9424-41a3-ae02-e129876c52db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>57fa0d82-9979-4b97-bcba-abe9ee0831ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Nanti Saja' or . = 'Nanti Saja')]</value>
      <webElementGuid>803173f2-7356-4723-8535-e9ba97fbd677</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
