<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kategori_option-wrapper</name>
   <tag></tag>
   <elementGuidId>8e6836ef-c93e-4501-8e1f-25a8d6eebf27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.option-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[2]/div/div[2]/form/fieldset/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>16e2a03f-ee86-4937-9d07-3fe3f7bd29b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option-wrapper</value>
      <webElementGuid>12883dfc-6e39-455b-9052-59dfdb045229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>option-right</value>
      <webElementGuid>bff9afb9-464c-4030-8358-257b53d643f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;min-h-screen flex flex-col bg-neutral-1000&quot;]/div[@class=&quot;text-neutral-600 mw-header w-full bg-neutral-1000 top-0 z-20 sticky&quot;]/div[@class=&quot;header-container md:p-5 pl-3 pr-3 border-b-1 border-t-1 border-neutral-800 bg-center bg-no-repeat&quot;]/div[@class=&quot;container mx-auto grid-cols-12 items-center grid&quot;]/div[@class=&quot;relative col-start-4 col-end-13 md:col-start-4 md:col-end-10 mr-0 md:mr-4&quot;]/form[1]/fieldset[@class=&quot;text-input border-none relative p-0&quot;]/div[@class=&quot;wrap flex items-center leading-0 bg-neutral-800 border-solid border-1 border-neutral-700 rounded h-13 no-label p-4 gap-2 pl-4 pr-2&quot;]/div[@class=&quot;option-wrapper&quot;]</value>
      <webElementGuid>bb017a4c-f390-4487-91c9-1749d4640a87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div[2]/form/fieldset/div/div[2]</value>
      <webElementGuid>8074d0b3-e34e-44ab-8940-2d5f727bdd8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::div[4]</value>
      <webElementGuid>5cb1a9aa-ad12-40df-b526-b228f7934511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favorit Saya'])[1]/following::div[11]</value>
      <webElementGuid>f9dae425-0ccf-458b-adab-f3b1b6c8186d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::div[7]</value>
      <webElementGuid>18b08807-bb18-4457-812c-3167abb82b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::div[8]</value>
      <webElementGuid>4016f80e-ce0e-4415-8d8d-af88891ccda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]</value>
      <webElementGuid>ffc85fed-9069-4076-b3ce-fa945349bf56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
