<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LIHAT SELENGKAPNYA_driver-page-overlay</name>
   <tag></tag>
   <elementGuidId>7f30ba9c-522e-4d36-86c9-36dc567f51ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#driver-page-overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='driver-page-overlay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>efa4ad7f-05de-4c45-819b-d44c37cf9a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>driver-page-overlay</value>
      <webElementGuid>2d2f6490-322d-49bd-b791-cd950d64583b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;driver-page-overlay&quot;)</value>
      <webElementGuid>8b56f87b-80b6-468d-8769-db410b04b5b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='driver-page-overlay']</value>
      <webElementGuid>1bb0352d-f193-4db1-b5b0-5546f746ffc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>ba215da4-dd58-4514-b9d7-31ea10d99022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'driver-page-overlay']</value>
      <webElementGuid>0b7e7706-1f4c-47ce-bc75-afa12f595f9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
