<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kategori_tracking-wide border-none bg_4c999e</name>
   <tag></tag>
   <elementGuidId>3f4f75f8-3711-49c3-bee3-fcb711407430</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.tracking-wide.border-none.bg-transparent.w-full.relative.text-sm.placeholder-neutral-500.text-neutral-300.search-bar.h-10.pt-6.pb-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32aa4927-afec-49aa-865c-904544c6a980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tracking-wide border-none bg-transparent w-full relative text-sm placeholder-neutral-500 text-neutral-300 search-bar h-10 pt-6 pb-2</value>
      <webElementGuid>61c13c86-e859-42e2-bc52-b0cd1e79b682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari di Jamtangan.com</value>
      <webElementGuid>9c7de1f9-880d-4d48-aef9-384be7ffe694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>search-input</value>
      <webElementGuid>6ce7423e-0f9e-44f8-8d7b-626d43517f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;min-h-screen flex flex-col bg-neutral-1000&quot;]/div[@class=&quot;text-neutral-600 mw-header w-full bg-neutral-1000 top-0 z-20 sticky&quot;]/div[@class=&quot;header-container md:p-5 pl-3 pr-3 border-b-1 border-t-1 border-neutral-800 bg-center bg-no-repeat&quot;]/div[@class=&quot;container mx-auto grid-cols-12 items-center grid&quot;]/div[@class=&quot;relative col-start-4 col-end-13 md:col-start-4 md:col-end-10 mr-0 md:mr-4&quot;]/form[1]/fieldset[@class=&quot;text-input border-none relative p-0&quot;]/div[@class=&quot;wrap flex items-center leading-0 bg-neutral-800 border-solid border-1 border-neutral-700 rounded h-13 no-label p-4 gap-2 pl-4 pr-2&quot;]/div[@class=&quot;w-full&quot;]/input[@class=&quot;tracking-wide border-none bg-transparent w-full relative text-sm placeholder-neutral-500 text-neutral-300 search-bar h-10 pt-6 pb-2&quot;]</value>
      <webElementGuid>078eed9d-e29f-4963-9da9-3680b5043a9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='']</value>
      <webElementGuid>6c051c57-3f64-43a2-88fe-39948b5036c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div[2]/form/fieldset/div/div/input</value>
      <webElementGuid>9f67947a-3b63-424b-b55e-a8eace5de770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9a313132-a9f4-4429-b452-edfe98c46270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Cari di Jamtangan.com']</value>
      <webElementGuid>08103c83-9926-4857-9f19-1de1dbb6a452</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
