<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>d0080196-c5ff-4394-81a1-d2b582032cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Alexandre Christie Primo Steel AC 1029 BRGSL Couple Silver Dial Rose Gold Stainless Steel Strap&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/section[2]/div[2]/div/div/div/div[2]/div/div/div/a/div/div/div/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>97620ab2-38e5-4306-aa74-42a69b0f2c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.jamtangan.com/images/product/alexandre-christie/ACF-1029-BRGSL/ACF-1029-BRGSL.jpg</value>
      <webElementGuid>18d18760-ad78-46db-9e4b-c3d8a1671812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Alexandre Christie Primo Steel AC 1029 BRGSL Couple Silver Dial Rose Gold Stainless Steel Strap</value>
      <webElementGuid>db0b0301-aa3a-41a3-9920-8bbaee2dc33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>229</value>
      <webElementGuid>9c7b1e76-42df-464e-93dd-e49c329bc121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>2fc10958-d06b-4f0e-a51d-f536b5ef89e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>1e0d5317-62cd-4001-a8d9-2c567b88a322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;min-h-screen flex flex-col bg-neutral-1000&quot;]/div[@class=&quot;mw-layout-content&quot;]/div[@class=&quot;homepage text-sm text-neutral-300 grid&quot;]/section[@class=&quot;featured-products mt-1 md:mt-3.5 px-4 md:px-0&quot;]/div[@class=&quot;lower&quot;]/div[@class=&quot;slick-slider product-slider active-slide-list slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active&quot;]/div[1]/div[@class=&quot;product p-2 h-full&quot;]/div[@class=&quot;relative h-full rounded-2 bg-neutral-900&quot;]/a[1]/div[@class=&quot;card relative rounded-2 bg-neutral-900 product-card-container cursor-pointer h-full&quot;]/div[@class=&quot;product-card relative&quot;]/div[@class=&quot;relative pt-6 px-2 md:px-4&quot;]/div[@class=&quot;box-img text-neutral-700 text-xs flex items-center&quot;]/picture[1]/img[1]</value>
      <webElementGuid>ca2427fe-2def-48c2-b264-e3a84d42f190</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/section[2]/div[2]/div/div/div/div[2]/div/div/div/a/div/div/div/div/picture/img</value>
      <webElementGuid>8633d5df-0de7-444b-81d2-0fe2ceeb8c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Alexandre Christie Primo Steel AC 1029 BRGSL Couple Silver Dial Rose Gold Stainless Steel Strap']</value>
      <webElementGuid>b51943d9-9e76-439f-977b-5589026df923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/div/div/div/div/picture/img</value>
      <webElementGuid>dac52ece-341e-435b-9276-fb85dedecac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.jamtangan.com/images/product/alexandre-christie/ACF-1029-BRGSL/ACF-1029-BRGSL.jpg' and @alt = 'Alexandre Christie Primo Steel AC 1029 BRGSL Couple Silver Dial Rose Gold Stainless Steel Strap']</value>
      <webElementGuid>9cfe1c73-3ab7-4b0d-806b-03ef21e27fdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
