<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EmailNo.Handphone_username</name>
   <tag></tag>
   <elementGuidId>6e92e40f-ac15-4b60-809c-20d928dde9fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;username&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ce70873-099c-4f8b-b109-69ced8ab1dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>c940abde-860b-4f8b-80ca-01ca2c7e12bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tracking-wide border-none bg-transparent w-full relative text-sm placeholder-neutral-500 text-neutral-300 h-10 pt-6 pb-2</value>
      <webElementGuid>594ee327-776e-4fca-bd73-e3b8478b4a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[1]/div[@class=&quot;modal fixed h-full w-full top-0 left-0 flex items-center justify-center bg-neutral-1000 bg-opacity-50&quot;]/div[@class=&quot;content relative bg-clip-padding outline-none&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;relative rounded-4 modal-container-wrap p-6 my-8 max-w-md bg-neutral-900&quot;]/div[@class=&quot;login-form-container&quot;]/div[@class=&quot;mx-auto my-0 text-neutral-200 login-form-popup p-3&quot;]/form[1]/div[@class=&quot;mb-5&quot;]/fieldset[@class=&quot;text-input border-none relative p-0 mb-2 qa-email-phone-field&quot;]/div[@class=&quot;wrap flex items-center leading-0 bg-neutral-800 border-solid border-1 border-neutral-700 rounded h-13 pl-4 pr-4&quot;]/div[@class=&quot;w-full&quot;]/input[@class=&quot;tracking-wide border-none bg-transparent w-full relative text-sm placeholder-neutral-500 text-neutral-300 h-10 pt-6 pb-2&quot;]</value>
      <webElementGuid>68abb534-1a7d-475e-8d71-9217b8efa523</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>68eaa61c-784e-4e6f-a6de-96008cefdc40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div/div/div/form/div/fieldset/div/div/input</value>
      <webElementGuid>6a8aa7a6-4ebe-4951-84ff-3e9618cca5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/fieldset/div/div/input</value>
      <webElementGuid>ee922308-9431-4368-b2e9-de752b50713f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username']</value>
      <webElementGuid>b33a48ab-e677-421d-a362-041c21285d41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
