<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verifikasi WhatsApp_w-12 p-3 text-cen_c67940</name>
   <tag></tag>
   <elementGuidId>214be181-a6a2-44c7-85da-e8498530b542</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.w-12.p-3.text-center.text-sm.text-neutral-300.bg-neutral-800.active.rounded.border-1.qa-otp-field.border-neutral-700</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cbd0653-3df5-4f88-8841-1f6fe9b27451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>65809790-7017-4476-a999-adbaa706d52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>4fd0ed3c-ef4d-4e0e-84ec-539c883fc3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0ed20c73-2c9b-4a58-8cbd-7881ab416b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-12 p-3 text-center text-sm text-neutral-300 bg-neutral-800 active rounded border-1 qa-otp-field border-neutral-700</value>
      <webElementGuid>befa68f1-ddeb-418c-8d97-b39386341922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c2b222ed-ca7e-43fe-bae3-6e059dbb3eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>otp-input-0</value>
      <webElementGuid>ba6519aa-2ff6-4b5c-899e-e4b9c8e8e7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>aaa8258f-4613-4ceb-b511-2731d6a39404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[2]/div[@class=&quot;modal fixed h-full w-full top-0 left-0 flex items-center justify-center bg-neutral-1000 bg-opacity-50&quot;]/div[@class=&quot;content relative bg-clip-padding outline-none&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;relative rounded-4 modal-container-wrap p-6 my-8 max-w-sm bg-neutral-900&quot;]/div[1]/div[1]/div[@class=&quot;mb-8&quot;]/div[@class=&quot;otp-input&quot;]/div[@class=&quot;flex flex-wrap&quot;]/div[@class=&quot;flex items-center flex-grow p-0.5&quot;]/input[@class=&quot;w-12 p-3 text-center text-sm text-neutral-300 bg-neutral-800 active rounded border-1 qa-otp-field border-neutral-700&quot;]</value>
      <webElementGuid>40ed372d-cecb-4038-9a27-e1e58af5338d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='6']</value>
      <webElementGuid>9476f683-2a0a-4c3a-b252-28e3dd5c1273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div[2]/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>716757b1-b1b4-4d96-841f-6d7329219ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>d55c8f4e-d8ca-493d-9312-f74b8a5491ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>245fb638-90e4-4717-94bc-df16078e1f5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
