<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_JT EZ   2-3 Hari</name>
   <tag></tag>
   <elementGuidId>c655e5fc-9c06-4167-a0b6-18109f36e433</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/main/section/div[2]/div[2]/div/ul/li[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>80498d40-947e-4f03-8f98-e5a16947d927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm uppercase tracking-wider</value>
      <webElementGuid>fccf2423-6d07-400e-8d26-c847ba8c354f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>J&amp;T EZ  | 2-3 Hari</value>
      <webElementGuid>0562d896-e672-41df-bd89-6efa617a87a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;min-h-screen flex flex-col bg-neutral-1000&quot;]/div[@class=&quot;mw-layout-content&quot;]/main[@class=&quot;container mx-auto md:grid md:grid-cols-3 md:mt-6 pb-20&quot;]/section[@class=&quot;md:col-span-2&quot;]/div[@class=&quot;relative p-4 md:p-6 md:rounded-2 md:mt-4 border-t-1 md:border-none border-neutral-800 bg-neutral-900&quot;]/div[@class=&quot;absolute right-6 z-10 top-20&quot;]/div[1]/ul[@class=&quot;overflow-auto px-2 md:px-0 border-neutral-700 md:border-1 md:rounded-2&quot;]/li[@class=&quot;bg-neutral-800 text-neutral-300 hover:text-primary-1 cursor-pointer py-4 pr-2 md:p-4 border-neutral-700 border-b-1&quot;]/div[@class=&quot;grid grid-cols-8 md:grid-cols-4&quot;]/div[@class=&quot;col-span-7 md:col-span-3&quot;]/div[@class=&quot;text-sm uppercase tracking-wider&quot;]</value>
      <webElementGuid>19fb62bc-24d0-47ef-a6d3-28158adc0854</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/main/section/div[2]/div[2]/div/ul/li[2]/div/div/div</value>
      <webElementGuid>4b4cca5d-4075-4d6b-832d-5bdce67067e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp126.000'])[1]/following::div[3]</value>
      <webElementGuid>237f4313-9ca1-4335-81ac-efb338b7d5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp94.000'])[1]/preceding::div[2]</value>
      <webElementGuid>918ba2a1-e940-47c8-bbe3-ac1b272ef76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='J&amp;T']/parent::*</value>
      <webElementGuid>775ff9ac-04ae-4baf-a5b8-3f782713d937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div</value>
      <webElementGuid>5e2164ad-fb02-49b4-bc32-0ed0dccf3b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'J&amp;T EZ  | 2-3 Hari' or . = 'J&amp;T EZ  | 2-3 Hari')]</value>
      <webElementGuid>80a9c206-595e-45ab-8420-41dcb706ca97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
