<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EmailNo.Handphone_username</name>
   <tag></tag>
   <elementGuidId>5770b8a4-d776-484f-9267-5fd9a0ab49f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;username&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f04349d4-b8d8-4174-9068-6e9cf0115926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>b68d6172-638f-440e-a8bb-41ec221863c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tracking-wide border-none bg-transparent w-full relative text-sm placeholder-neutral-500 text-neutral-300 h-10 pt-6 pb-2</value>
      <webElementGuid>f2a1e53b-a619-416e-baab-5d94c87a6a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[1]/div[@class=&quot;modal fixed h-full w-full top-0 left-0 flex items-center justify-center bg-neutral-1000 bg-opacity-50&quot;]/div[@class=&quot;content relative bg-clip-padding outline-none&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;relative rounded-4 modal-container-wrap p-6 my-8 max-w-md bg-neutral-900&quot;]/div[@class=&quot;login-form-container&quot;]/div[@class=&quot;mx-auto my-0 text-neutral-200 login-form-popup p-3&quot;]/form[1]/div[@class=&quot;mb-5&quot;]/fieldset[@class=&quot;text-input border-none relative p-0 mb-2 qa-email-phone-field&quot;]/div[@class=&quot;wrap flex items-center leading-0 bg-neutral-800 border-solid border-1 border-neutral-700 rounded h-13 pl-4 pr-4&quot;]/div[@class=&quot;w-full&quot;]/input[@class=&quot;tracking-wide border-none bg-transparent w-full relative text-sm placeholder-neutral-500 text-neutral-300 h-10 pt-6 pb-2&quot;]</value>
      <webElementGuid>cfd45e95-004a-4ab9-92a5-6dab472e42e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>d8719fd5-7a62-4ead-a6df-88803aed7c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div/div/div/form/div/fieldset/div/div/input</value>
      <webElementGuid>8d96bf9a-00fe-4b50-b863-f144e8f853a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/fieldset/div/div/input</value>
      <webElementGuid>6c3bbf43-640d-420c-b911-933447945ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username']</value>
      <webElementGuid>650d181c-64e6-46bc-a05e-15d6208b3d46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
