<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verifikasi WhatsApp_w-12 p-3 text-cen_c67940</name>
   <tag></tag>
   <elementGuidId>d58afc5a-4c84-49cc-8781-3f138677b99e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.w-12.p-3.text-center.text-sm.text-neutral-300.bg-neutral-800.active.rounded.border-1.qa-otp-field.border-neutral-700</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d87902ad-621e-4114-af2f-4599477c5e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c63220c9-b84a-4f9e-b1c2-cc2c3075043e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>2597cde5-eb9e-4e5e-9bea-208412b77b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3789e3a6-660a-4da8-8f5c-cb360a8b60b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-12 p-3 text-center text-sm text-neutral-300 bg-neutral-800 active rounded border-1 qa-otp-field border-neutral-700</value>
      <webElementGuid>23e9aa96-0f51-407c-b515-e4b295c80c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d3f61f74-915c-4fc6-8a7f-62b6a251830a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>otp-input-0</value>
      <webElementGuid>070c40b5-f3cb-405e-92fb-f85e195e8327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>32fa46d7-fc71-4419-978e-4e9f9f5106e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[2]/div[@class=&quot;modal fixed h-full w-full top-0 left-0 flex items-center justify-center bg-neutral-1000 bg-opacity-50&quot;]/div[@class=&quot;content relative bg-clip-padding outline-none&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;relative rounded-4 modal-container-wrap p-6 my-8 max-w-sm bg-neutral-900&quot;]/div[1]/div[1]/div[@class=&quot;mb-8&quot;]/div[@class=&quot;otp-input&quot;]/div[@class=&quot;flex flex-wrap&quot;]/div[@class=&quot;flex items-center flex-grow p-0.5&quot;]/input[@class=&quot;w-12 p-3 text-center text-sm text-neutral-300 bg-neutral-800 active rounded border-1 qa-otp-field border-neutral-700&quot;]</value>
      <webElementGuid>318d11ea-3029-4c1d-95d5-1d071d56e13b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='4']</value>
      <webElementGuid>5d7422a6-12a4-4af3-abd6-2d1a81eedc15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div[2]/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>deccdaa1-fd7a-4bf8-a53a-2cfe949d49a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>7d98daf3-6bc8-46f5-8c07-f5c1461da65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>e38fb2ad-ba41-41a2-86b6-50a44e4f4ac1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
